name: "PlateVision"
slug: platevision
description: Lokale Kennzeichen-, Fahrzeug- und Personenerkennung für Home Assistant
version: "0.9.0"
url: "https://github.com/richieam93/platevision-ha-addon"
arch:
  - amd64
startup: services
boot: auto
init: false

ports:
  5000/tcp: 8087
ports_description:
  5000/tcp: PlateVision Web UI

webui: "http://[HOST]:[PORT:8087]"
