name: "PlateVision"
slug: platevision
description: PlateVision 
version: "0.8.5"
arch:
  - amd64
startup: services
boot: auto
init: false

ports:
  5000/tcp: 8087
ports_description:
  5000/tcp: PlateVision Web UI

webui: "http://[HOST]:[PORT:8087]"
